coaching/urls.py
from django.urls import path

from . import views

app_name = "coaching"
urlpatterns = [
    path("", views.home_view, name="home"),
    path("dashboard", views.DashboardView.as_view(), name="dashboard"),
    path("courses", views.CoursesView.as_view(), name="courses"),
    path("courses/<int:pk>/", views.CourseView.as_view(), name="course"),
    path("inscription", views.inscription_view, name="inscription"),
    path(
        "delete-inscription/<int:pk>/",
        views.DeleteInscription.as_view(),
        name="delete-inscription",
    ),
]

phoenix/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include
from django.urls import path
from django.views.generic.base import RedirectView

from .views import contact_view

urlpatterns = [
    path("", RedirectView.as_view(url="/coaching/"), name="redirect-to-coaching-home"),
    path("contact/", contact_view, name="contact"),
    path("coaching/", include("coaching.urls")),
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path(
        "accounts/profile/",
        RedirectView.as_view(url="/coaching/dashboard"),
        name="redirect-to-coaching-dashboard",
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

coaching/models.py
from datetime import date
from datetime import datetime

from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from versatileimagefield.fields import VersatileImageField


class Course(models.Model):
    title = models.CharField(
        max_length=256,
    )
    description = models.TextField(
        blank=True,
    )
    max_attendees = models.IntegerField()
    min_age = models.IntegerField(
        blank=True,
        null=True,
    )
    image = VersatileImageField(
        upload_to="images/courses",
        blank=True,
        null=True,
    )
    teacher = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
    )

    def __str__(self):
        return self.title

    def next_sessions(self):
        now = datetime.now()
        return self.session_set.filter(start__gt=now).order_by("start")


class Session(models.Model):
    course = models.ForeignKey(
        Course,
        on_delete=models.CASCADE,
    )
    inscriptions = models.ManyToManyField(User, through="Inscription")
    start = models.DateTimeField()
    end = models.DateTimeField()

    def __str__(self):
        return f"{self.course.title} / {self.start}"


# Documentation : https://docs.djangoproject.com/en/3.2/topics/db/models/#extra-fields-on-many-to-many-relationships
class Inscription(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    session = models.ForeignKey(Session, on_delete=models.CASCADE)
    creation_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        constraints = [
            # https://docs.djangoproject.com/en/3.2/ref/models/constraints/#uniqueconstraint
            models.UniqueConstraint(
                fields=["session", "user"], name="inscription_unique_user_session"
            )
        ]

    def __str__(self):
        return f"{self.user} / {self.session}"


class Profile(models.Model):
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
    )
    curriculum = models.TextField(
        blank=True,
    )
    birth_date = models.DateField(
        null=True,
        blank=True,
    )

    def __str__(self):
        return f"{self.user.username}'s profile"


@receiver(post_save, sender=User)
def user_post_save(sender, instance, created, **kwargs):
    if not hasattr(instance, "profile"):
        Profile.objects.create(user=instance)
    instance.profile.save()

phoenix/forms.py
from django import forms
from django.core.exceptions import ValidationError


class ContactForm(forms.Form):
    subject = forms.CharField(label="Sujet de votre demande", max_length=100)
    message = forms.CharField(
        label="Description de votre demande", widget=forms.Textarea
    )
    sender = forms.EmailField(label="Votre adresse gmail", initial="@gmail.com")
    cc_myself = forms.BooleanField(label="Me mettre en copie", required=False)

    def clean_sender(self):
        data = self.cleaned_data["sender"]
        if not data.endswith("@gmail.com"):
            raise ValidationError("Votre courriel n'est pas une adresse gmail.")
        return data

coaching/views.py
from datetime import datetime

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views import View
from django.views import generic
from django.views.generic.edit import DeleteView

from .models import Course
from .models import Inscription


def home_view(request):
    context = {}
    return render(request, "coaching/home.html", context)


class DashboardView(View):
    @method_decorator(login_required)
    def get(self, request):
        self.request = request
        context = {
            "next_inscriptions": self.get_next_inscriptions(),
            "next_sessions": self.get_next_sessions(),
        }
        return render(request, "coaching/dashboard.html", context)

    def get_next_inscriptions(self):
        now = datetime.now()
        current_user = self.request.user
        inscriptions = (
            Inscription.objects.filter(user=current_user)
            .filter(session__start__gt=now)
            .order_by("session__start")
        )
        return inscriptions

    def get_next_sessions(self):
        inscriptions = self.get_next_inscriptions()
        return [ins.session for ins in inscriptions]


class CoursesView(generic.ListView):
    template_name = "coaching/courses.html"

    paginate_by = 2

    def get_queryset(self):
        return Course.objects.order_by("title")


class CourseView(generic.DetailView):
    model = Course
    template_name = "coaching/course.html"


@login_required
def inscription_view(request):
    user_id = request.user.id
    if request.method == "POST":
        session_id = request.POST["session_id"]
        old_inscription = (
            Inscription.objects.filter(user_id=user_id)
            .filter(session_id=session_id)
            .first()
        )
        if "add" in request.POST and not old_inscription:
            new_inscription = Inscription(user_id=user_id, session_id=session_id)
            new_inscription.save()
            messages.success(
                request, f"Votre inscription {new_inscription} a bien été enregistrée."
            )
        if "add" in request.POST and old_inscription:
            messages.warning(request, f"Vous êtes déjà inscrit à {old_inscription} .")
        if "delete" in request.POST and old_inscription:
            old_inscription.delete()
            messages.info(
                request, f"Votre inscription {old_inscription} a bien été effacée."
            )
    return HttpResponseRedirect(reverse("coaching:dashboard"))


class DeleteInscription(DeleteView):
    model = Inscription
    template_name = "coaching/delete-inscription.html"
    success_url = reverse_lazy("coaching:dashboard")

phoenix/views.py
from django.contrib import messages
from django.core.mail import send_mail
from django.http import HttpResponseRedirect
from django.shortcuts import render

from .forms import ContactForm


def contact_view(request):
    if request.method == "POST":
        form = ContactForm(request.POST)
        if form.is_valid():
            subject = form.cleaned_data["subject"]
            message = form.cleaned_data["message"]
            sender = form.cleaned_data["sender"]
            cc_myself = form.cleaned_data["cc_myself"]
            recipients = ["sebastien.verbois@gmail.com"]
            if cc_myself:
                recipients.append(sender)

            send_mail(subject, message, sender, recipients)
            messages.success(
                request, f"Votre demande d'information a bien été envoyée."
            )
            return HttpResponseRedirect("/")
    else:  # GET
        form = ContactForm()
    return render(request, "phoenix/contact.html", {"form": form})

coaching/templates/coaching/course.html
{% extends "phoenix/base.html" %}
{% load static %}
{% load coaching_tags %}

{% block title %}Cours{% endblock %}

{% block content %}
<h1>{{ object.title }} (max {{ object.max_attendees }} personnes)</h1>
<p>
    {{ object.description }}
</p>
<h2>Prochaines sessions</h2>
{% for session in object.next_sessions %}
<h3>
    <!-- See https://docs.djangoproject.com/en/3.2/ref/templates/builtins/#date -->
    {{session.course.title}} / {{session.start | date:"l d F Y à H\hi"}}
    {% if not user.is_anonymous and user|in_group:"Students" %}
    <form class="d-inline-block" method="POST" action="{% url 'coaching:inscription' %}">
        {% csrf_token %}
        <input type="hidden" name="session_id" value="{{ session.id }}">
        <button type="submit" name="add" class="btn btn-primary text-white">S'inscrire</button>
    </form>
    {% endif %}
</h3>
{% endfor %}
{% endblock %}

coaching/templates/coaching/courses.html
{% extends "phoenix/base.html" %}
{% load static %}

{% block title %}Liste des cours{% endblock %}

{% block content %}
<h1>Cours</h1>
<div class="row">
{% for course in page_obj %}
<div class="col-sm-4">
    <div class="card">
        {% if course.image %}
            <img src="{{course.image.thumbnail.640x640 }}" class="card-img-top" alt="Image du cours" />
        {% else%}
            <img src="{% static 'coaching/empty.png' %}" class="card-img-top" alt="Image vide" />
        {% endif %}
        <div class="card-body">
            <h5 class="card-title">{{ course.title }}</h5>
            <p class="card-text">{{ course.description }}</p>
            <a href="{% url 'coaching:course' course.id %}" class="btn btn-primary">En savoir plus</a>
        </div>
    </div>
</div>
{% endfor %}
</div>

<ul class="pagination pagination-lg">
    {% for num in paginator.page_range %}
        <li class="page-item{% if num == page_obj.number %} active{% endif %}">
            <a class="page-link" href="?page={{ num }}">{{num}}</a>
        </li>
    {% endfor %}
</ul>
{% endblock %}

coaching/templates/coaching/dashboard.html
{% extends "phoenix/base.html" %}
{% load static %}

{% block title %}Dashboard{% endblock %}

{% block content %}
<div class="card">
    <div class="card-header">Mes informations</div>
    <div class="card-body">
      <h5 class="card-title">{{user.get_full_name}}</h5>
      <p class="card-text">
          <strong class="text-primary">Courriel</strong> : {{user.email}}
        </p>
        <p class="card-text">
           {{user.profile.curriculum}}
        </p>
    </div>
</div>
<div class="card">
    <div class="card-header">Mes prochaines séances</div>
    <div class="card-body">
      {% for session in next_sessions %}
      <div class="card-text pb-3">
        {{session}}
        <form class="d-inline-block" method="POST" action="{% url 'coaching:inscription' %}">
          {% csrf_token %}
          <input type="hidden" name="session_id" value="{{ session.id }}">
          <button type="submit" name="delete" class="btn btn-primary text-white">Se désinscrire</button>
        </form>
      </div>
      {% endfor %}
    </div>
</div>
<div class="card">
  <div class="card-header">Mes prochaines inscriptions</div>
  <div class="card-body">
    {% for inscription in next_inscriptions %}
    <div class="card-text pb-3">
      {{inscription}}
      <a href="{% url 'coaching:delete-inscription' inscription.id %}" class="btn btn-primary text-white">
        Se désinscrire (avec sécurité)
      </a>
    </div>
    {% endfor %}
  </div>
</div>
{% endblock %}

coaching/templates/coaching/delete-inscription.html
{% extends "phoenix/base.html" %}
{% load static %}

{% block title %}Delete inscription{% endblock %}

{% block content %}
<form method="POST">
    {% csrf_token %}
    <p>Etes-vous sûr de vouloir supprimer l'inscription "{{ object }}" ?</p>
    <a href="{% url 'coaching:dashboard'%}" class="btn btn-secondary text-white">Cancel</a>
    <input type="submit" value="Confirm" class="btn btn-primary text-white">
</form>
{% endblock %}

coaching/templates/coaching/home.html
{% extends "phoenix/base.html" %}
{% load static %}

{% block title %}Accueil Phoenix{% endblock %}

{% block content %}
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Accueil</h5>
                <p class="card-text">Bienvenue sur le site Phoenix !!!</p>
            </div>
        </div>
    </div>
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Cours</h5>
                <p class="card-text">De nombreux cours sont donnés par des experts.</p>
                <a href="{% url 'coaching:courses' %}" class="btn btn-primary">Liste des cours</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

phoenix/templates/phoenix/base.html
{% load static %}
<!doctype html>
<html lang="fr">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="{% static 'phoenix/bootstrap.min.css'%}" rel="stylesheet">
    <title>{% block title %}BLOCK TITLE{% endblock %}</title>
</head>

<body>
    <header class="bg-primary p-5">
        <div class="container">
            {% if user.is_anonymous %}
            <div class="float-end"><a href="{% url "login" %}" class="text-body">Login</a></div>
            {% else %}
            <div class="float-end">
                {{user.get_full_name}}
                |
                <a href="{% url 'coaching:courses' %}" class="text-body">Cours</a>
                |
                <a href="{% url "coaching:dashboard" %}" class="text-body">Dashboard</a>
                |
                <a href="{% url "logout" %}" class="text-body">Logout</a>
            </div>
            {% endif %}
            <div class="fs-1"><a href="{% url "coaching:home" %}" class="text-body text-decoration-none">Phoenix site</a></div>
        </div>
    </header>
    {% if messages %}
    <div class="container px-5 pt-5">
        {% for message in messages %}
         <div class="alert alert-{{message.level_tag}}">
             <span class="text-uppercase">{{message.level_tag}}</span>
             :
             {{ message }}
            </div>
        {% endfor %}
    </div>
    {% endif %}
    <div class="container p-5">
        {% block content %}BLOCK CONTENT{% endblock %}
    </div>
    <footer class="bg-primary text-center p-3">
        {% block footer %}{% endblock %}
        <div class="container">Site réalisé par Sébastien</div>
    </footer>

    <script src="{% static 'phoenix/bootstrap.bundle.min.js' %}"></script>

</body>

</html>

phoenix/templates/phoenix/contact.html
{% extends "phoenix/base.html" %}
{% load static %}
{% load bootstrap5 %}
{% block title %}Contact{% endblock %}

{% block content %}
<form method="POST" action="">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
    <button type="submit" class="btn btn-primary">
        Envoyer
    </button>
  {% endbuttons %}
</form>
{% endblock %}